#!/usr/bin/env ruby

ENV['RAILS_ENV'] = case ARGV.first
  when "p": "production"
  when "d": "development"
  when "t": "test"
  else
    ARGV.first || ENV['RAILS_ENV'] || 'development'
end

require File.dirname(__FILE__) + '/../config/boot'
require File.dirname(__FILE__) + '/../config/environment'
require 'open-uri'

last_twit = Twit.first(:order => "twitid desc")
url = "http://search.twitter.com/search.json?q=protip:&rpp=100&since_id=#{last_twit.twitid}"
puts "getting --[ #{url} ]"
open(url) do |f|
  twits = Twit.create_from_string(f.read)
  puts "--[ #{twits.length} twits added ]"
end
